In [2]:
!pip install otter-grader
!pip install Levenshtein
!pip install pandas

Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple


In [8]:
# Initialize Otter
import otter
grader = otter.Notebook("2022201538.ipynb")

# Labs01: Exercises with NumPy and Pandas

In [17]:
import numpy as np
import Levenshtein
import pandas as pd
import matplotlib.pyplot as plt
np.random.seed(44)

## Preliminary Exercises

**exercise1:** Array Creation

- Make an array `arr1` of shape (10,20) with the array elements filled with 1
- Make an array `arr2` of shape (10,20) with the array elements filled with 0
- Make an array `arr3` with 100 evenly spaced values between 0 and 2 * pi
- Make an array `arr4` which contains the cosine of the corresponding value in x, so arr4[i] = cos(arr3[i])

In [21]:
arr1 = np.ones((10,20))
arr2 = np.zeros((10,20))
arr3 = np.linspace(0, 2 * np.pi, 100)
arr4 = np.cos(arr3)

In [22]:
grader.check("pre_e1")

pre_e1 results: All test cases passed!

**exercise2:** Indexing and slicing

- Create the following array, call this `arr5`

```python
        2  7  12  0
        3  9  3  4
        4  0  1  3
```

- Get the $2^{nd}$ row of a ([ 3 9 3 4]), call this `arr6`
- Get the $3^{rd}$ column of a ([12 3 1]), call this `arr7`
- Use `>` to make a mask `arr8` that is true where the elements are greater than 5, like this:

```python
        False True  True  False
        False True  False False
        False False False False
```

- Set all the elements greater than 5 to be equal to 5 with the above mask and call it `arr9    `, to get this:

```python
        2  5  5  0
        3  5  3  4
        4  0  1  3
```

In [38]:
arr5 = np.array([[2,7,12,0],[3,9,3,4],[4,0,1,3]])
arr6 = arr5[1]
arr7 = arr5[:,2]
arr8 = arr5>5
arr9=np.copy(arr5)
arr9[arr9>5]=5
print(arr9)

[[2 5 5 0]
 [3 5 3 4]
 [4 0 1 3]]


In [39]:
grader.check("pre_e2")

pre_e2 results: All test cases passed!

**exercise3:** Construct pandas.Dataframe and other numpy exercises

1. construct Dataframe object named `A` and `B` with pandas from `A.csv` and `B.csv`



```
        for A:
        {'id': {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}, 
            'Beer_Name': {0: 'Honey Basil Amber', 1: 'Freedom Soho Red', 2: 'Jazz Beer Tarraco Amber', 3: 'Sanibel Red Island Ale', 4: 'Real McCoy Amber Ale', 5: 'River Otter Ale', 6: 'The Gentle Mongoose', 7: 'Arrow Point Amber', 8: 'River Otter Ale', 9: 'Rip Saw Red'}, 
            'Brew_Factory_Name': {0: 'Rude Hippo Brewing Company', 1: 'Freedom Brewery Ltd', 2: 'Tarraco Beer', 3: 'Point Ybel Brewing Company', 4: 'Mammoth Brewing Company', 5: 'Union Station Brewery', 6: 'Holy City Brewing', 7: 'Bainbridge Island Brewing Company', 8: 'Union Station Brewery', 9: 'Pints Brewing Co. .'}, 
            'Style': {0: 'American AmberRed Ale', 1: 'American AmberRed Ale', 2: 'American AmberRed Ale', 3: 'American AmberRed Ale', 4: 'American AmberRed Ale', 5: 'American AmberRed Ale', 6: 'American AmberRed Ale', 7: 'American AmberRed Ale', 8: 'American AmberRed Ale', 9: 'American AmberRed Ale'}, 
            'ABV': {0: 7.4, 1: 4.7, 2: 6.9, 3: 5.6, 4: 4.5, 5: 5.1, 6: 6.9, 7: 5.4, 8: 5.1, 9: 6.5}}
```



```
        for B:
        {'id': {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19}, 
            'Beer_Name': {0: 'Tongue Buckler - Imperial Red Ale', 1: 'Rude Hippo Honey Basil Amber', 2: 'Three Heads Buffalo Soul Jah Imperial Red Ale', 3: 'Freedom Soho Red', 4: 'Hop Around Imperial Red Ale', 5: 'Jazz Beer Tarraco Amber', 6: 'Marble Imperial Red Ale', 7: 'Point Ybel Sanibel Red Island Ale', 8: 'Smuttynose Kindest Find Imperial Red Ale', 9: 'Mammoth Real McCoy Amber Ale', 10: 'Rock Bottom Orland Park King of Hearts Imperial Red Ale', 11: 'Sacramento River Otter Ale', 12: 'Smuttynose Kindest Find Imperial Red Ale', 13: 'Holy City The Gentle Mongoose', 14: 'Brannon_s Deputation Imperial Red Ale', 15: 'Bainbridge Island Arrow Point Amber', 16: 'Red Dirt Imperial Red Ale', 17: 'Sacramento River Otter Ale', 18: 'AleSmith YuleSmith 40; Winter 41; Imperial Red Ale', 19: 'Pints Rip Saw Red'}, 
            'Brew_Factory_Name': {0: 'Ballast Point Brewing Company', 1: '18th Street Brewery', 2: 'Custom Brewcrafters', 3: 'Freedom', 4: 'Big Bay Brewing Co. .', 5: 'Ca l_Arenys - Cervezas Guineu', 6: 'Marble Brewery', 7: 'Point Ybel Brewing Company', 8: 'Smuttynose Brewing Company', 9: 'Mammoth Brewing Company', 10: 'Rock Bottom Orland Park', 11: 'Sacramento Brewing Company', 12: 'Smuttynose Brewing Company', 13: 'Holy City Brewing', 14: 'Brannon_s Pub and Brewery', 15: 'Bainbridge Island Brewing Company', 16: 'Wiley Roots Brewing Co', 17: 'Sacramento Brewing Company', 18: 'AleSmith Brewing Company', 19: 'Pints Brewing Company'}, 
            'Style': {0: 'American AmberRed Ale', 1: 'Amber Ale', 2: 'American Strong Ale', 3: 'Amber LagerVienna', 4: 'American AmberRed Ale', 5: 'Amber Ale', 6: 'American Strong Ale', 7: 'Irish Ale', 8: 'American AmberRed Ale', 9: 'Altbier', 10: 'American Strong Ale', 11: 'English Pale Ale', 12: 'American AmberRed Ale', 13: 'Amber Ale', 14: 'American Strong Ale', 15: 'Amber Ale', 16: 'American AmberRed Ale', 17: 'English Pale Ale', 18: 'American Strong Ale', 19: 'Amber Ale'}, 
            'ABV': {0: 10.0, 1: 7.4, 2: 9.2, 3: 4.7, 4: 9.0, 5: 6.9, 6: 9.0, 7: 5.6, 8: 8.5, 9: 4.5, 10: 7.6, 11: 5.5, 12: 8.5, 13: 6.9, 14: 8.79, 15: 5.4, 16: 8.2, 17: 5.5, 18: 8.5, 19: 5.9}}
```

2. construct numpy.array object `a3` as below.



```python
        a3:
        0   1
        1   3
        2   5
        3   7
        ...
        9   19
```

<font color='red'> Note: You need to create it according to the steps provided below; otherwise, some test cases may not pass. And the resulting seed should have a shape of (10,2). </font>

In [74]:
A = pd.DataFrame.from_dict({'id': {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}, 
            'Beer_Name': {0: 'Honey Basil Amber', 1: 'Freedom Soho Red', 2: 'Jazz Beer Tarraco Amber', 3: 'Sanibel Red Island Ale', 4: 'Real McCoy Amber Ale', 5: 'River Otter Ale', 6: 'The Gentle Mongoose', 7: 'Arrow Point Amber', 8: 'River Otter Ale', 9: 'Rip Saw Red'}, 
            'Brew_Factory_Name': {0: 'Rude Hippo Brewing Company', 1: 'Freedom Brewery Ltd', 2: 'Tarraco Beer', 3: 'Point Ybel Brewing Company', 4: 'Mammoth Brewing Company', 5: 'Union Station Brewery', 6: 'Holy City Brewing', 7: 'Bainbridge Island Brewing Company', 8: 'Union Station Brewery', 9: 'Pints Brewing Co. .'}, 
            'Style': {0: 'American AmberRed Ale', 1: 'American AmberRed Ale', 2: 'American AmberRed Ale', 3: 'American AmberRed Ale', 4: 'American AmberRed Ale', 5: 'American AmberRed Ale', 6: 'American AmberRed Ale', 7: 'American AmberRed Ale', 8: 'American AmberRed Ale', 9: 'American AmberRed Ale'}, 
            'ABV': {0: 7.4, 1: 4.7, 2: 6.9, 3: 5.6, 4: 4.5, 5: 5.1, 6: 6.9, 7: 5.4, 8: 5.1, 9: 6.5}})
B = pd.DataFrame.from_dict({'id': {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19}, 
            'Beer_Name': {0: 'Tongue Buckler - Imperial Red Ale', 1: 'Rude Hippo Honey Basil Amber', 2: 'Three Heads Buffalo Soul Jah Imperial Red Ale', 3: 'Freedom Soho Red', 4: 'Hop Around Imperial Red Ale', 5: 'Jazz Beer Tarraco Amber', 6: 'Marble Imperial Red Ale', 7: 'Point Ybel Sanibel Red Island Ale', 8: 'Smuttynose Kindest Find Imperial Red Ale', 9: 'Mammoth Real McCoy Amber Ale', 10: 'Rock Bottom Orland Park King of Hearts Imperial Red Ale', 11: 'Sacramento River Otter Ale', 12: 'Smuttynose Kindest Find Imperial Red Ale', 13: 'Holy City The Gentle Mongoose', 14: 'Brannon_s Deputation Imperial Red Ale', 15: 'Bainbridge Island Arrow Point Amber', 16: 'Red Dirt Imperial Red Ale', 17: 'Sacramento River Otter Ale', 18: 'AleSmith YuleSmith 40; Winter 41; Imperial Red Ale', 19: 'Pints Rip Saw Red'}, 
            'Brew_Factory_Name': {0: 'Ballast Point Brewing Company', 1: '18th Street Brewery', 2: 'Custom Brewcrafters', 3: 'Freedom', 4: 'Big Bay Brewing Co. .', 5: 'Ca l_Arenys - Cervezas Guineu', 6: 'Marble Brewery', 7: 'Point Ybel Brewing Company', 8: 'Smuttynose Brewing Company', 9: 'Mammoth Brewing Company', 10: 'Rock Bottom Orland Park', 11: 'Sacramento Brewing Company', 12: 'Smuttynose Brewing Company', 13: 'Holy City Brewing', 14: 'Brannon_s Pub and Brewery', 15: 'Bainbridge Island Brewing Company', 16: 'Wiley Roots Brewing Co', 17: 'Sacramento Brewing Company', 18: 'AleSmith Brewing Company', 19: 'Pints Brewing Company'}, 
            'Style': {0: 'American AmberRed Ale', 1: 'Amber Ale', 2: 'American Strong Ale', 3: 'Amber LagerVienna', 4: 'American AmberRed Ale', 5: 'Amber Ale', 6: 'American Strong Ale', 7: 'Irish Ale', 8: 'American AmberRed Ale', 9: 'Altbier', 10: 'American Strong Ale', 11: 'English Pale Ale', 12: 'American AmberRed Ale', 13: 'Amber Ale', 14: 'American Strong Ale', 15: 'Amber Ale', 16: 'American AmberRed Ale', 17: 'English Pale Ale', 18: 'American Strong Ale', 19: 'Amber Ale'}, 
            'ABV': {0: 10.0, 1: 7.4, 2: 9.2, 3: 4.7, 4: 9.0, 5: 6.9, 6: 9.0, 7: 5.6, 8: 8.5, 9: 4.5, 10: 7.6, 11: 5.5, 12: 8.5, 13: 6.9, 14: 8.79, 15: 5.4, 16: 8.2, 17: 5.5, 18: 8.5, 19: 5.9}})

a1 = np.arange(10)# Create an array with 10 elements ranging from 0 to 9
a2 = np.arange(20) # Create an array with 20 elements ranging from 0 to 19
a2 =a2[a2%2==1]# Filter the odd numbers in a2 so that the elements of a2 are 1,3,5,...,19, there are 10 numbers
# Intermediate code can be written to perform operations such as reshape()
a3 = np.concatenate((a1, a2))  # Concatenate a1 and a2 to produce the resulting seeds object as shown in the markdown code block above
a3=a3.reshape(2,-1).T

In [62]:
grader.check("pre_e3")

pre_e3 results: All test cases passed!

## Exercise1: Define a rule-based EA model

**Entity Alignmen:** Entity Alignment (EA) is an important task in the fields of Natural Language Processing (NLP) and Knowledge Graphs, with its primary objective being to map (correspond) entities from different knowledge graphs or data sources to equivalent entities in each other.

**Exercise Introduction:** In this exercise, you are required to use the Pandas library to read data from a CSV file and create the corresponding test dataset. In this experiment, we assume there are two knowledge bases, A and B, which store data only about beers, and the data is highly structured. Therefore, for the convenience of data reading, we will no longer provide the data in the form of knowledge graph triples but instead present the data in the form of relational tables.

**Example:** The first 5 rows of A and B are shown as below.

A: 
id|Beer_Name|Brew_Factory_Name|Style|ABV
------- | ------- | ------- | ------- | -------
0 | Honey Basil Amber | Rude Hippo Brewing Company | American AmberRed Ale | 7.4
1 | Freedom Soho Red | Freedom Brewery Ltd | American AmberRed Ale | 4.7
2 | Jazz Beer Tarraco Amber | Tarraco Beer | American AmberRed Ale | 6.9
3 | Sanibel Red Island Ale | Point Ybel Brewing Company | American AmberRed Ale | 5.6
4 | Real McCoy Amber Ale | Mammoth Brewing Company | American AmberRed Ale | 4.5

B:
id | Beer_Name | Brew_Factory_Name | Style | ABV
---|-----------|-------------------|-------|----
0 | Tongue Buckler - Imperial Red Ale | Ballast Point Brewing Company | American AmberRed Ale | 10.0
1 | Rude Hippo Honey Basil Amber | 18th Street Brewery | Amber Ale | 7.4
2 | Three Heads Buffalo Soul Jah Imperial Red Ale | Custom Brewcrafters | American Strong Ale | 9.2
3 | Freedom Soho Red | Freedom | Amber LagerVienna | 4.7
4 | Hop Around Imperial Red Ale | Big Bay Brewing Co. . | American AmberRed Ale | 9.0

$Entity_0$ in A is a `American AmberRed Ale`(Beer) named `Honey Basil Amber` produced by `Rude Hippo Brewing Company` whose `ABV` is 7.4.

$Entity_1$ in B is a `Amber Ale`(Beer) named `Rude Hippo Honey Basil Amber` produced by `18th Street Brewery` whose `ABV` is 7.4.

- Style: The only difference is that $Entity_1$ in B has omitted attributes.
- Name: Same thing in different format.
- Brew_Factory_Name: Rude Hippo Brewing Company and 18th Street Brewery refer to the same Brew Factory actually.
- ABV: Exactly the same.

Thus, $Entity_0$ in A and $Entity_1$ in B are actually the same entity in real world.

**Construct an EA dataset from DataFrame A and DataFrame B.** If we look through all entities in A and B, we can find that:

- $Entity_0$ in A and $Entity_1$ in B are the same.
- $Entity_1$ in A and $Entity_3$ in B are the same.
- $Entity_2$ in A and $Entity_5$ in B are the same.
- $Entity_3$ in A and $Entity_7$ in B are the same.
- ...

We can use an numpy array named `seeds` to record the alignment results as:

```python
        0   1
        1   3
        2   5
        3   7
        ...
        9   19
```

We can notice that `seeds` is identical to `a3` in the previous exercise.

In [125]:
seeds = a3
seeds

array([[ 0,  1],
       [ 1,  3],
       [ 2,  5],
       [ 3,  7],
       [ 4,  9],
       [ 5, 11],
       [ 6, 13],
       [ 7, 15],
       [ 8, 17],
       [ 9, 19]])

**Step1:** Define a function that inputs two strings and outputs their string Levenstein ratio as the similarity.(call `Levenshtein.ratio(str1, str2)`)

In [64]:
def string_sim(str1, str2):
    return Levenshtein.ratio(str1,str2)

In [66]:
grader.check("ex1_q1")

ex1_q1 results: All test cases passed!

**Step2:** Implement $model_{EA}$。

given two entities $e_1=[p_1^1,p_2^1,...,p_n^1]$ and $e_2=[p_1^2,p_2^2,...,p_n^2]$ and a string similarity function $sim()$, $model_{EA}$ is defined as below.
$$model_{EA}(e_1,e_2)=\frac{1}{n}\sum_{i=1}^n sim(p_i^1,p_i^2)$$

Use the python language to implement this model.

In [116]:
def model_EA(e1, e2):
    sims = [] # build a list to save similarities of all properties between e1 and e2
    # traverse all properties(except `id` property) in e1,e2
    for i in range(1,len(e1)) :
        # calculate similarity of properties with similarity function `string_sim(str1,str2)`
        #if type(e1[i])!=str:
        #    continue
        t=string_sim(str(e1[i]),str(e2[i]))
        # append the calculated similarity to `sims`
        sims.append(t)
    # calculate the average similarities and return it
    return (1/len(sims))*(sum(sims))

e1 = A.iloc[0]
e2 = B.iloc[1]
print(e1)
sim_of_entities = model_EA(e1, e2)
print(sim_of_entities)
model_EA(A.iloc[0], B.iloc[1])
print(model_EA(A.iloc[0], B.iloc[3]))

id                                            0
Beer_Name                     Honey Basil Amber
Brew_Factory_Name    Rude Hippo Brewing Company
Style                     American AmberRed Ale
ABV                                         7.4
Name: 0, dtype: object
0.6666666666666666
0.3098086124401914


In [118]:
grader.check("ex1_q2")

ex1_q2 results: All test cases passed!

## Exercise2: Calculate Hit@k of the model

**Step1:** obtain similarity matrix `mat`
- type: numpy.array
- shape: (len_A, len_B)
- mat[i][j]: represents the similarity between $entity_i$ in A and $entity_j$ in B

In [122]:
# mat[i][j] represents the similarity between entity i in A and entity j in B
mat = np.ones((len(A),len(B)))
for i in range(len(A)):
    for j in range(len(B)):
        mat[i][j]=model_EA(A.iloc[i], B.iloc[j])

In [124]:
grader.check("ex2_q1")

ex2_q1 results: All test cases passed!

**Step2:** Calculate Hit@k

Hit@k indicates whether the correct matching entity is included in the first k candidate entities. For example, there are the following data.

entity|candidates(sorted by sim)
-|-
$a_1$|$b_2,b_1,b_3$
$a_2$|$b_2,b_3,b_1$
$a_3$|$b_1,b_2,b_3$

The actual matching results are: $(a_1,b_1),(a_2,b_2),(a_3,b_3)$

Then $hit@1=1/3=0.33$, because only the second row matches successfully in the first candidate entity; $hit@2=2/3=0.67$, because the second and first rows match successfully in the first two candidate entities.

Define a function that, given the value of $k$, outputs the $hit@k$ of $model_{EA}$.

Note: If you do not want to follow the belowing procedures in Prompt, you can try `np.argsort()`, which may bring you surprise for concise codes.

In [151]:
def hit_k(mat, seeds, k=1):
    # Iterate through each row of the array `seeds` and get seed `(l, r)`
    # try to sort similarity array(mat[l]) of Entity l in A and record the corresponding indexes of each elements
    # record the original indexes of top-k highest similarities, if r in these indexes, count += 1
    # return count/len(seeds)
    count=0
    for l,r in seeds:
        s=np.argsort(-mat[l],axis=0)
        s=s[0:k]
        if r in s:
            count+=1
    return count/len(seeds)
hit_k(mat,seeds,k=2)
        

0.9

In [155]:
grader.check("ex2_q2")


ex2_q2 results: All test cases passed!